<a href="https://colab.research.google.com/github/jiw3026/baseline_/blob/main/05_%E1%84%87%E1%85%AE%E1%86%AB%E1%84%85%E1%85%B2_%E1%84%86%E1%85%A9%E1%84%83%E1%85%A6%E1%86%AF_%E1%84%8B%E1%85%B5%E1%84%92%E1%85%A2(NaiveBayes).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 나이브 베이즈 분류기
사이킷런에 구현된 나이브 베이즈 분류기는 0.22버전을 기준으로 GaussianNB, BernoulliNB, MultinomialNB, ComplementNB, CategoricalNB 5가지 이다.

In [ ]:
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 39.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.6/465.6 KB 18.9 MB/s eta 0:00:00


In [ ]:
# matplotlib 설정
from matplotlib import pyplot as plt
from matplotlib import rc
import numpy as np

%matplotlib inline

# rc('font', family = 'AppleGothic')
# plt.rcParams['axes.unicode_minus'] = False
# # mac OS 에서 한글이 깨진다면 참고.

### 가우시안 나이브 베이즈

- GaussianNB의 경우 연속적인 데이터를 처리하는 용도로 많이 사용된다.  

### 다항 분포, 베르누이 나이브 베이즈

- BernoulliNB, MultinomialNB는 문서분류와 같은 곳에서 많이 사용된다.  

베르누이는 문서에 단어가 출현을 했는지 여부를 따져서 문서를 벡터화 시킨다. 이와 다르게 다항 분포는 단어의 출현횟수를 기록한다.

- 베르누이와 다항분포에는 alpha라는 매개변수가 있다. alpha는 스무딩(smoothing)의 정도를 조절할 수 있다.  
- 그럼 스무딩은 무엇인가? 입력값이 우리가 가지고 있는 훈련데이터에는 없는 값이 들어올 경우 확률이 0이 되어 정상적인 분류가 되지 않는 경우가 생긴다.  
이런 경우를 방지하고자 값을 보정하기 위해 사용되는 기법이 스무딩 기법이다.(라플라스 계산을 사용한다.), 라플라스를 이용하여 특징값이 최소한 한 번은 나타나도록 조정하여 특징값이 0이 될 수 없도록 한다.  
- alpha매개변수는 알고리즘의 성능에 크게 영향을 미치지는 않지만, 값을 조정하면 정확도를 어느정도 높일수는 있다.

In [ ]:
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB


In [ ]:
from konlpy.tag import Okt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

x_data = ['설문조사하고 백화점 상품권 받아가자',
        '응모권 발급되었어요 응모하시고 천만원 받아가세요', 
        '다음 예약시 할인 가능',
        '피자먹고 유럽투어 가자',
        '블랙프라이데이 한정 세일',
        '머신생명 보험 상담 받으시고 안마의자 받아가세요',
        '회원님 장바구니에 들어있는 제품 할인행사 안내',
        '오늘 아침회의 내용 정리 보고서입니다',
        '5시까지 업무 보고서 제출하세요',
        '이번달 보험료 청구금액은',
        '다음주 일정 확인 부탁드립니다',
         '이번 달 카드 사용 청구서']
y_data = [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]

labels = ['햄', '스팸']
# 간단하게 데이터를 만들어 베르누이 나이브 베이즈를 실습해보자.
# 자연어처리에 관한 설명은 여기서 다루지 않도록 하겠다.

In [ ]:
for i, d in enumerate(x_data):
    n_words = Okt().nouns(d) # 명사만 추출
    x_data[i] = ' '.join(n_words)

In [ ]:
print(n_words)

['이번', '달', '카드', '사용', '청구']


In [ ]:
vectorizer = CountVectorizer()
vectorizer.fit(x_data)
x_data = vectorizer.transform(x_data)
print(x_data.shape)

(12, 43)


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, 
                                                    test_size=0.3, shuffle = True, 
                                                    stratify = y_data)

ber_model = BernoulliNB().fit(X_train, y_train)

print('train score : {}'.format(ber_model.score(X_train, y_train)))
print('test score : {}'.format(ber_model.score(X_test, y_test)))

train score : 1.0
test score : 0.5


In [ ]:
ber_model.classes_

array([0, 1])

In [ ]:
ber_model.class_count_

array([4., 4.])

In [ ]:
ber_model.class_log_prior_
# 사전 확률 분포 로그 값 (베르누이와 다항 분포에서만 사용.)

array([-0.69314718, -0.69314718])

In [ ]:
new_data = '초특가 할인행사에 괌 여행 응모권까지 받아가자'
n_words = Okt().nouns(new_data)
n_words = ' '.join(n_words)
print(n_words)

초특 할인 행사 괌 여행 응모


In [ ]:
n_data = [n_words]
X1 = vectorizer.transform(n_data)
print(X1) 

  (0, 24)	1
  (0, 38)	1
  (0, 39)	1


In [ ]:
ber_model_pred = ber_model.predict(X1)
print('예측한 값 : {}'.format(ber_model_pred)) 
print('스팸인가?, 아닌가? : {}'.format(labels[ber_model_pred[0]]))

예측한 값 : [0]
스팸인가?, 아닌가? : 햄


- MultinomialNB로 예측

In [ ]:
multi_naive = MultinomialNB().fit(X_train, y_train)

print('train score : {}'.format(multi_naive.score(X_train, y_train)))
print('test score : {}'.format(multi_naive.score(X_test, y_test)))

train score : 1.0
test score : 0.5


In [ ]:
multi_naive.classes_

array([0, 1])

In [ ]:
multi_naive.class_count_

array([4., 4.])

In [ ]:
model_pred = multi_naive.predict(X1)
print('예측한 값 : {}'.format(model_pred)) 
print('스팸인가?, 아닌가? : {}'.format(labels[model_pred[0]]))

예측한 값 : [0]
스팸인가?, 아닌가? : 햄



- CategoricalNB : 범주형으로 분포되어 있고 이산 특징을 가진 데이터를 분류하는데 적합한 모델이다.(0.22 ver 부터 구현가능)  
- ComplementNB : 다항분포 나이브 베이즈가 만들어낸 'severe assumptions'을 수정하도록 만들어 졌다. 특히나 불균형 데이터에 매우 적합한 모델이다. (0.20 ver부터 구현가능)